### PR TITLE
Add QB-Target integration and small fixes

### PR DESCRIPTION
**Pull request by deandum**

### CODE REVIEW

**Comment by BerkieBb** [comment]
Everything looks good, but I have a small suggestion, whej not using the target but using drawtext from qb-core, you could add `exports['qb-core']:KeyPressed()` after the control press if statement to add an animation after pressing a control, also if you do this, add a `Wait(500)` to make the animation play and then do the rest like hiding the text, that's what I do with qb-cityhall for example, small touch but it looks nice

**Comment by deandum** [comment]
> Everything looks good, but I have a small suggestion, whej not using the target but using drawtext from qb-core, you could add `exports['qb-core']:KeyPressed()` after the control press if statement to add an animation after pressing a control, also if you do this, add a `Wait(500)` to make the animation play and then do the rest like hiding the text, that's what I do with qb-cityhall for example, small touch but it looks nice

Thanks! I will look into adding that. I want to add Emglish locale anyway.

**Comment by GhzGarage** [comment]
Not sure if this is finished but debugPoly is on true

**Comment by deandum** [comment]
> Not sure if this is finished but debugPoly is on true

It is ready now. I had to do some small cleanup since my IDE decided to completely reformat the file and I included the comments from @BerkieBb. Also, I don't see any `debugPoly` on true. Am I missing something?

**Review by BerkieBb — APPROVED** [review]
Don't seem to see any debugPoly = true

**Pull request merged**
